Repository PQClean/PQClean, pull requests merged in 2019-07, with the labels that each got.

#203 Change sha3_512_inc_finalize output length to 64
  common/fips202.c
Labels: bug

#211 Fix documentation for Dilithium `crypto_sign_open`
  crypto_sign/dilithium2/clean/sign.c
  crypto_sign/dilithium3/clean/sign.c
  crypto_sign/dilithium4/clean/sign.c
Labels: ready for review

#212 Create SECURITY.md
  SECURITY.md
Labels: enhancement, ready for review

#200 Move test support files into tests directory
  test/Makefile
  test/Makefile.Microsoft_nmake
  test/common/nistkatrng.c
  test/common/notrandombytes.c
  test/test_common.py
  test/test_common/aes.c
  test/test_common/fips202.c
  test/test_common/sha2.c
  test/test_common/sp800-185.c
Labels: ready for review

#206 Parallel tests
  .circleci/config.yml
  .gitignore
  .travis.yml
  README.md
  appveyor.yml
  requirements.txt
  test/helpers.py
  test/pqclean.py
  test/pytest.ini
  test/test_api_h.py
  test/test_char.py
  test/test_common.py
  test/test_compile_lib.py
  test/test_duplicate_consistency.py
  test/test_dynamic_memory.py
  test/test_format.py
  test/test_functest.py
  test/test_license.py
  test/test_linter.py
  test/test_makefile_dependencies.py
  test/test_makefiles_present.py
  test/test_metadata.py
  test/test_metadata_sizes.py
  test/test_nistkat.py
  test/test_no_symlinks.py
  test/test_preprocessor.py
  test/test_symbol_namespace.py
  test/test_testvectors.py
  test/test_valgrind.py
Labels: ready for review
