Repository PQClean/PQClean, pull requests merged in 2019-04, with the labels that each got.

#78 Add FrodoKEM-640-SHAKE reference implementation
  .clang-tidy
  crypto_kem/frodokem640shake/META.yml
  crypto_kem/frodokem640shake/clean/LICENSE
  crypto_kem/frodokem640shake/clean/Makefile
  crypto_kem/frodokem640shake/clean/Makefile.Microsoft_nmake
  crypto_kem/frodokem640shake/clean/api.h
  crypto_kem/frodokem640shake/clean/common.h
  crypto_kem/frodokem640shake/clean/kem.c
  crypto_kem/frodokem640shake/clean/matrix_shake.c
  crypto_kem/frodokem640shake/clean/noise.c
  crypto_kem/frodokem640shake/clean/params.h
  crypto_kem/frodokem640shake/clean/util.c
  test/Makefile
  test/crypto_kem/functest.c
  test/crypto_sign/functest.c
  test/test_compile_lib.py
Labels: enhancement, ready for review

#67 Enable some extra warnings
  test/Makefile
Labels: question

#104 test_format wasn't actually checking output of astyle
  crypto_kem/frodokem1344shake/clean/util.c
  crypto_kem/frodokem640shake/clean/util.c
  crypto_kem/frodokem976shake/clean/util.c
  test/test_format.py
Labels: ready for review

#103 Filter tests when diff'ing against master branch
  test/helpers.py
  test/pqclean.py
Labels: ready for review

#109 Add -Wmissing-prototypes
  README.md
  common/aes.c
  crypto_kem/frodokem1344aes/clean/Makefile
  crypto_kem/frodokem1344aes/clean/noise.c
  crypto_kem/frodokem1344aes/clean/util.c
  crypto_kem/frodokem1344shake/clean/Makefile
  crypto_kem/frodokem1344shake/clean/noise.c
  crypto_kem/frodokem1344shake/clean/util.c
  crypto_kem/frodokem640aes/clean/Makefile
  crypto_kem/frodokem640aes/clean/noise.c
  crypto_kem/frodokem640aes/clean/util.c
  crypto_kem/frodokem640shake/clean/Makefile
  crypto_kem/frodokem640shake/clean/noise.c
  crypto_kem/frodokem640shake/clean/util.c
  crypto_kem/frodokem976aes/clean/Makefile
  crypto_kem/frodokem976aes/clean/noise.c
  crypto_kem/frodokem976aes/clean/util.c
  crypto_kem/frodokem976shake/clean/Makefile
  crypto_kem/frodokem976shake/clean/noise.c
  crypto_kem/frodokem976shake/clean/util.c
  crypto_kem/kyber768/clean/Makefile
  crypto_kem/kyber768/clean/verify.c
  crypto_sign/sphincs-shake256-128f-simple/clean/Makefile
  crypto_sign/sphincs-shake256-128f-simple/clean/address.c
  test/Makefile
Labels: ready for review

#105 Add ntruhps2048509
  crypto_kem/ntruhps2048509/META.yml
  crypto_kem/ntruhps2048509/clean/LICENSE
  crypto_kem/ntruhps2048509/clean/Makefile
  crypto_kem/ntruhps2048509/clean/Makefile.Microsoft_nmake
  crypto_kem/ntruhps2048509/clean/api.h
  crypto_kem/ntruhps2048509/clean/crypto_sort.c
  crypto_kem/ntruhps2048509/clean/crypto_sort.h
  crypto_kem/ntruhps2048509/clean/kem.c
  crypto_kem/ntruhps2048509/clean/owcpa.c
  crypto_kem/ntruhps2048509/clean/owcpa.h
  crypto_kem/ntruhps2048509/clean/pack3.c
  crypto_kem/ntruhps2048509/clean/packq.c
  crypto_kem/ntruhps2048509/clean/params.h
  crypto_kem/ntruhps2048509/clean/poly.c
  crypto_kem/ntruhps2048509/clean/poly.h
  crypto_kem/ntruhps2048509/clean/sample.c
  crypto_kem/ntruhps2048509/clean/sample.h
  crypto_kem/ntruhps2048509/clean/verify.c
  crypto_kem/ntruhps2048509/clean/verify.h
Labels: ready for review

#117 Be more selective in test runs
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  test/Makefile
  test/crypto_kem/functest.c
  test/crypto_sign/functest.c
  test/helpers.py
  test/pqclean.py
  test/test_api_h.py
  test/test_char.py
  test/test_common.py
  test/test_compile_lib.py
  test/test_duplicate_consistency.py
  test/test_dynamic_memory.py
  test/test_format.py
  test/test_functest.py
  test/test_license.py
  test/test_linter.py
  test/test_makefile_dependencies.py
  test/test_metadata.py
  test/test_metadata_sizes.py
  test/test_nistkat.py
  test/test_no_symlinks.py
  test/test_preprocessor.py
  test/test_symbol_namespace.py
  test/test_testvectors.py
  test/test_valgrind.py
Labels: ready for review
