Repository PQClean/PQClean, pull requests merged in 2020-02, with the labels that each got.

#267 Fix alignment problems with vectors in McEliece AVX2 and fix McEliece 8192128f
  crypto_kem/mceliece348864/avx/int32_sort.c
  crypto_kem/mceliece348864f/META.yml
  crypto_kem/mceliece348864f/avx/int32_sort.c
  crypto_kem/mceliece460896/avx/bm.c
  crypto_kem/mceliece460896/avx/int32_sort.c
  crypto_kem/mceliece460896f/avx/bm.c
  crypto_kem/mceliece460896f/avx/int32_sort.c
  crypto_kem/mceliece6688128/avx/bm.c
  crypto_kem/mceliece6688128/avx/int32_sort.c
  crypto_kem/mceliece6688128f/avx/bm.c
  crypto_kem/mceliece6688128f/avx/int32_sort.c
  crypto_kem/mceliece6960119/avx/bm.c
  crypto_kem/mceliece6960119/avx/int32_sort.c
  crypto_kem/mceliece6960119f/avx/bm.c
  crypto_kem/mceliece6960119f/avx/int32_sort.c
  crypto_kem/mceliece8192128/avx/bm.c
  crypto_kem/mceliece8192128/avx/int32_sort.c
  crypto_kem/mceliece8192128f/META.yml
  crypto_kem/mceliece8192128f/avx/bm.c
  crypto_kem/mceliece8192128f/avx/consts.inc
  crypto_kem/mceliece8192128f/avx/decrypt.c
  crypto_kem/mceliece8192128f/avx/fft.c
  crypto_kem/mceliece8192128f/avx/fft_tr.c
  crypto_kem/mceliece8192128f/avx/int32_sort.c
  crypto_kem/mceliece8192128f/avx/pk_gen.c
  crypto_kem/mceliece8192128f/avx/powers.inc
  crypto_kem/mceliece8192128f/avx/scalars_4x.inc
Labels: ready for review

#265 Move keys in crypto_sign/functest.c to the heap
  test/crypto_kem/functest.c
  test/crypto_sign/functest.c
Labels: ready for review

#272 Fix memory leak in Kyber
  crypto_kem/kyber1024-90s/clean/indcpa.c
  crypto_kem/kyber1024/avx2/symmetric.h
  crypto_kem/kyber1024/clean/indcpa.c
  crypto_kem/kyber1024/clean/symmetric.h
  crypto_kem/kyber512-90s/clean/indcpa.c
  crypto_kem/kyber512/avx2/symmetric.h
  crypto_kem/kyber512/clean/indcpa.c
  crypto_kem/kyber512/clean/symmetric.h
  crypto_kem/kyber768-90s/clean/indcpa.c
  crypto_kem/kyber768/avx2/indcpa.c
  crypto_kem/kyber768/avx2/symmetric.h
  crypto_kem/kyber768/clean/indcpa.c
  crypto_kem/kyber768/clean/symmetric.h
Labels: bug

#274 Fix detecting of to-be-tested changes on Windows
  test/helpers.py
Labels: CI, bug, ready for review
